---
DISABLE_LINTERS:
  - SPELL_CSPELL
SHOW_ELAPSED_TIME: true
ENABLE_LINTERS:
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - DOCKERFILE_HADOLINT
ANSIBLE_DIRECTORY: .
PRE_COMMANDS:
  - command: pip install requests
    venv: requests
